name: instagram_clone
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  image_picker: ^1.0.5
  provider: ^6.1.1
  uuid: ^4.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/ic_instagram.svg
